// Counter actions
export const INCREMENT_COUNTER = 'INCREMENT_COUNTER'
export const DECREMENT_COUNTER = 'DECREMENT_COUNTER'
export const RESET_COUNTER = 'RESET_COUNTER'
// Theme actions
export const SWITCH_TO_DARK_THEME = 'SWITCH_TO_DARK_THEME'
export const SWITCH_TO_LIGHT_THEME = 'SWITCH_TO_LIGHT_THEME'